// This file is auto-generated by the ObjectEditorGenerator. Changes may be overwritten.
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine.UIElements;
using System.Collections.Generic;

public class MockDataObjectGeneratedEditor : ObjectManagementEditor<MockDataObject>
{
    [MenuItem("Tools/Generated Editors/MockDataObject Editor")]
    public static void ShowWindow()
    {
        var window = GetWindow<MockDataObjectGeneratedEditor>();
        window.titleContent = new UnityEngine.GUIContent("MockDataObject Editor");
    }

    // A set containing the names of the properties to be displayed.
    private readonly HashSet<string> _propertiesToShow = new HashSet<string>
    {
        "itemName",
        "description",
        "itemType",
        "isUnique",
        "value",
        "weight",
    };

    protected override void DrawDetailsPanelContent(SerializedObject serializedObject, VisualElement parent)
    {
        // Iterate over all serialized properties of the object.
        var property = serializedObject.GetIterator();
        property.NextVisible(true); // Start with the first visible property.

        do
        {
            // If the property's name is in our set, create a field for it.
            if (_propertiesToShow.Contains(property.name))
            {
                var propertyField = new PropertyField(property.Copy());
                propertyField.Bind(serializedObject);
                // The PropertyField will automatically bind to the property.
                parent.Add(propertyField);
            }
        } while (property.NextVisible(false));
    }
}
#endif
