// This file is auto-generated by the ObjectEditorGenerator. Changes may be overwritten.
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine.UIElements;
using System.Collections.Generic;

public class UnitGeneratedEditor : ObjectManagementEditor<Unit>
{
    [MenuItem("Tools/Generated Editors/Unit Editor")]
    public static void ShowWindow()
    {
        var window = GetWindow<UnitGeneratedEditor>();
        window.titleContent = new UnityEngine.GUIContent("Unit Editor");
    }

    private readonly HashSet<string> _propertiesToShow = new HashSet<string>
    {
        "unitName",
        "health",
        "attackDamage",
        "attackRange",
        "attackType",
    };

    protected override void DrawDetailsPanelContent(SerializedObject serializedObject, VisualElement parent)
    {
        // Iterate over all serialized properties of the object.
        var property = serializedObject.GetIterator();
        property.NextVisible(true); // Start with the first visible property.

        do
        {
            // If the property's name is in our set, create a field for it.
            if (_propertiesToShow.Contains(property.name))
            {
                var propertyField = new PropertyField(property.Copy());
                propertyField.Bind(serializedObject);
                // The PropertyField will automatically bind to the property.
                parent.Add(propertyField);
            }
        } while (property.NextVisible(false));
    }
}
#endif
